### PR TITLE
Add cc & bcc fields

### PR DESCRIPTION
**Pull request by SonnyBA**
These fields will only be used to store information. I also pulled in the changes from [Yubin](https://github.com/APSL/django-yubin) in this branch as this fork hasn't been updated in a long time.

### CODE REVIEW

**Comment by SonnyBA** [comment]
For the record, the last [commit](https://github.com/maykinmedia/django-yubin/pull/2/commits/dec0fb62570021eb75efcbb6bd4bf056053466a1) in this PR is actually the change which was done compared to the latest Yubin version.

**Comment by sergei-maertens** [comment]
@SonnyBA I've updated master from our fork with upstream master, this cleans up the PR considerably.

It looks like the changes made by Alex were merged in upstream already, so we could discard those.

What's the nature of this PR? Should this be contributed back upstream? That would be my preference as django-yubin still seems to be well-maintained.

**Comment by alextreme** [comment]
I'd approve this change for our usage, however if the goal is to merge this upstream I suspect they won't like to hardcode yubin to only work on Postgres (the PR makes use of ArrayField). 

@SonnyBA feel free to discuss this with Sergei, I agree with him that if upstream is responsive we should do some additional effort to also have our changes merged and avoid depending on our fork.

**Comment by SonnyBA** [comment]
@sergei-maertens @alextreme I have my doubts that they will find these additions useful upstream. This basically only adds new fields which don't have any meaning to them (other than storing information).

@sergei-maertens To add some context to this PR, for an application we wanted to save (and show) the `cc` and `bcc` recipients for emails. The `cc` could have been shown through the emails headers (stored in the `encoded_message` field on the `Message` model) but this is not the case for the `bcc` recipients (hence this PR).

**Comment by alextreme** [comment]
@SonnyBA in that case lets go for a separate 'wba' branch for these changes. Then we can keep our master in sync with upstream.

**Comment by sergei-maertens** [comment]
@SonnyBA just a thought, but maybe you could skip this patch alltogether and use django-timeline-logger to relate extra information to an `EmailMessage`? Bit more complicated in your end-project, but might be favourable over maintaining a fork.

**Comment by alextreme** [comment]
Thanks for the tip, we already use timeline-logger but for this purpose it would require quite a refactor for the project. I'd prefer a (light) fork.

**Comment by SonnyBA** [comment]
I"m closing this PR as I've created a [separate branch](https://github.com/maykinmedia/django-yubin/tree/wba) as suggested.

**Pull request closed without merging**
